![imagen](./img/ejercicios.png)

In [3]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [4]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
print(my_array[::-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [7]:
print(my_array)
print(my_array[-2:-4:-1])

[0 1 2 3 4 5 6 7 8 9]
[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [8]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [12]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [13]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [14]:
print(np.flip(my_matrix))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [15]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [16]:
print(my_matrix[:2,:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [35]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [83]:
print(my_matrix[::2,::2])

[[ 1  3  5]
 [11 13 15]]


In [94]:
my_matrix[[True,False,True,False],:][:,[True,False,True,False,True]]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [95]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [96]:
print(my_matrix[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [97]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [98]:
print(x == "Loro")

[ True False False  True False]


In [99]:
print(x[x == "Loro"])

['Loro' 'Loro']


In [102]:
x[np.where(x=="Loro")]

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [104]:
x = np.arange(20).reshape(2,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [109]:
print(x.ndim)
print(x.shape)
print(x.size)

3
(2, 5, 2)
20


## Ejercicio 10 (reptido con el 4.2)
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [112]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [146]:
x = np.zeros(10)
# x = np.full(10, 0)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [147]:
print(x.itemsize)
print(x.nbytes)
print(x.dtype)

8
80
float64


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [149]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [150]:
print(x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [152]:
ejer_13 = np.array([1,2,0,0,4,0])

print(type(ejer_13))

<class 'numpy.ndarray'>


In [155]:
np.where(ejer_13 != 0)

(array([0, 1, 4], dtype=int64),)

In [154]:
ejer_13[np.where(ejer_13 != 0)]

array([1, 2, 4])

In [171]:
def ejercicio_13(vector):
    return np.where(vector != 0)[0]

In [172]:
print(type(ejercicio_13(ejer_13)))

<class 'numpy.ndarray'>


In [162]:
ejercicio_13(ejer_13)

array([0, 1, 4], dtype=int64)

In [164]:
ejercicio_13(np.array([4,2,0,5,0,4]))

array([0, 1, 3, 5], dtype=int64)

In [174]:
np.nonzero(ejer_13)[0]

array([0, 1, 4], dtype=int64)

In [175]:
def ejercicio_13(vector):
    return np.nonzero(ejer_13)[0]

In [176]:
ejercicio_13(np.array([4,2,0,5,0,4]))

array([0, 1, 4], dtype=int64)

## Ejercicio 14
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [220]:
# np.random.seed(14)
x = np.random.randint(100, size=(10,10))
print(x)
print(np.min(x))
print(x.min())
print(np.max(x))
print(x.max())

[[63  4 75 95 56 26 49 28 38  8]
 [98 28 65 79 34  0 90 48 27 43]
 [43 67 19 19 91 78 38 74 78 29]
 [42 34 34 78 36 71 39 22 73 30]
 [83 72 92 21 82 61  2 67 83 36]
 [55 36 53 39  9 19 28 68 67 99]
 [89 92 37 50 46 93 63  7  0 58]
 [53 48 84  4 78 89 81 32 30 99]
 [71 31 95 46 41 54 86 14 82 90]
 [ 1 93 87 57 90 49 34 48 10 77]]
0
0
99
99


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [222]:
x = np.random.random(30)
print(x)

[0.25539501 0.60749416 0.06326907 0.57147345 0.09147925 0.52053415
 0.59765241 0.77264137 0.52511203 0.63927514 0.54036689 0.26558244
 0.31097849 0.44307113 0.37684685 0.56731838 0.41287517 0.95340193
 0.59667902 0.47408603 0.99549954 0.22539378 0.45432185 0.43419766
 0.76055761 0.57153618 0.68805618 0.41197644 0.21742303 0.14686675]


In [223]:
print(x.sum()/len(x))

0.4830453786520472


In [226]:
print(np.mean(x))

0.4830453786520472


In [227]:
print(x.mean())

0.4830453786520472


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [239]:
ejer_16 = np.ones((10,10))
print(ejer_16)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [240]:
ejer_16[1:-1, 1:-1] = 0
print(ejer_16)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [246]:
def ejercicio_16(shape:tuple):
    x = np.ones((shape[0],shape[1]))
    x[1:-1, 1:-1] = 0
    return x

In [249]:
ejercicio_16((3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [254]:
x = np.zeros((8,8))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [256]:
x[::2,1::2] = 1
x[1::2,::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [258]:
for i in range(len(x)):
    for j in range(len(x[i])):
        print(i)
        print(j)
        print("-"*10)

0
0
----------
0
1
----------
0
2
----------
0
3
----------
0
4
----------
0
5
----------
0
6
----------
0
7
----------
1
0
----------
1
1
----------
1
2
----------
1
3
----------
1
4
----------
1
5
----------
1
6
----------
1
7
----------
2
0
----------
2
1
----------
2
2
----------
2
3
----------
2
4
----------
2
5
----------
2
6
----------
2
7
----------
3
0
----------
3
1
----------
3
2
----------
3
3
----------
3
4
----------
3
5
----------
3
6
----------
3
7
----------
4
0
----------
4
1
----------
4
2
----------
4
3
----------
4
4
----------
4
5
----------
4
6
----------
4
7
----------
5
0
----------
5
1
----------
5
2
----------
5
3
----------
5
4
----------
5
5
----------
5
6
----------
5
7
----------
6
0
----------
6
1
----------
6
2
----------
6
3
----------
6
4
----------
6
5
----------
6
6
----------
6
7
----------
7
0
----------
7
1
----------
7
2
----------
7
3
----------
7
4
----------
7
5
----------
7
6
----------
7
7
----------


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [260]:
a = np.array([[0,1],[1,0]])
print(a)

[[0 1]
 [1 0]]


In [266]:
x = np.tile(a, (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [278]:
x = np.random.randint(1,20, (5,5))
print(x)

[[ 7 12  9 15  4]
 [16 12  9  8 17]
 [10 11  3 11 14]
 [17  1 18 11 17]
 [19 14 12  4 13]]


In [279]:
x = ((x - np.mean(x))/ np.std(x))

In [280]:
print(x)

[[-0.90538307  0.13290027 -0.49006974  0.75587027 -1.52835307]
 [ 0.96352694  0.13290027 -0.49006974 -0.6977264   1.1711836 ]
 [-0.28241307 -0.0747564  -1.73600974 -0.0747564   0.5482136 ]
 [ 1.1711836  -2.15132308  1.37884027 -0.0747564   1.1711836 ]
 [ 1.58649694  0.5482136   0.13290027 -1.52835307  0.34055693]]


In [281]:
print(x.mean())
print(x.std())

1.176836406102666e-16
0.9999999999999998


In [282]:
1 * 10 ** (-16)

1e-16

In [288]:
1*10**(-4)

0.0001

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [311]:
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [312]:
y = x.copy()

In [313]:
y[(y > 3) & (y < 8)] = -1
print(y)

[ 0  1  2  3 -1 -1 -1 -1  8  9 10]


In [ ]:
# & and
# | or

In [314]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [315]:
z = x.copy()

z[(z > 3) & (z < 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
