# Getting and Knowing your Data



### Step 1. Import the necessary libraries

In [3]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user) and assign it to a variable called users. Use pd.read_csv()

In [63]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user"

users = pd.read_csv(url, sep="|", index_col="user_id")

In [64]:
print(users)

         age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]


In [10]:
print(type(users))

<class 'pandas.core.frame.DataFrame'>


In [14]:
print(type(users['age']))

<class 'pandas.core.series.Series'>


### Step 3. See the first 25 entries


In [27]:
users.head(25)

age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

### Step 4. See the first 25 entries in a differente way

In [39]:
users.loc[:25]

age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

In [40]:
users.iloc[:25]

age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

In [51]:
users.head(5)

age gender  occupation zip_code
user_id                                 
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213

In [67]:
users.loc[2:4, "gender":"occupation"]

gender  occupation
user_id                   
2            F       other
3            M      writer
4            M  technician

In [69]:
users.iloc[2:4, 1:3]

gender  occupation
user_id                   
3            M      writer
4            M  technician

In [37]:
# users.loc[2:5,"gender":"occupation"]

gender  occupation
user_id                   
2            F       other
3            M      writer
4            M  technician
5            F       other

In [38]:
# users.iloc[2:5,1:3]

gender  occupation
user_id                   
3            M      writer
4            M  technician
5            F       other

In [32]:
# np.array(users)[0:5]

array([[24, 'M', 'technician', '85711'],
       [53, 'F', 'other', '94043'],
       [23, 'M', 'writer', '32067'],
       [24, 'M', 'technician', '43537'],
       [33, 'F', 'other', '15213']], dtype=object)

### Step 5. See the last 10 entries

In [42]:
step5 = users.tail(10)

In [43]:
step5

age gender     occupation zip_code
user_id                                    
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

In [44]:
print(type(step5))

<class 'pandas.core.frame.DataFrame'>


### Step 6. What is the number of observations in the dataset?
Solve it by 2 different ways

In [82]:
len(users)

943

In [77]:
users.shape[0]

943

In [83]:
len(users.index)

943

### Step 7. What is the number of columns in the dataset?
Solve it by 2 different ways

In [85]:
users.shape[1]

4

In [88]:
len(users.columns)

4

In [95]:
# users.columns.shape

In [97]:
print(np.array(users.columns))

['age' 'gender' 'occupation' 'zip_code']


### Step 8. Print the name of all the columns.

In [98]:
for x in users.columns:
    print(x)

age
gender
occupation
zip_code


In [99]:
l_col = list(users.columns)
print(*l_col)

age gender occupation zip_code


In [100]:
print(users.columns)

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')


### Step 9. How is the dataset indexed? Get the index values

In [106]:
users.index

Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
            ...
            934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
           dtype='int64', name='user_id', length=943)

In [107]:
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

In [108]:
users.values

array([[24, 'M', 'technician', '85711'],
       [53, 'F', 'other', '94043'],
       [23, 'M', 'writer', '32067'],
       ...,
       [20, 'M', 'student', '97229'],
       [48, 'F', 'librarian', '78209'],
       [22, 'M', 'student', '77841']], dtype=object)

In [109]:
np.array(users)

array([[24, 'M', 'technician', '85711'],
       [53, 'F', 'other', '94043'],
       [23, 'M', 'writer', '32067'],
       ...,
       [20, 'M', 'student', '97229'],
       [48, 'F', 'librarian', '78209'],
       [22, 'M', 'student', '77841']], dtype=object)

In [113]:
for i in np.array(users):
    print(i)
    for j in i:
        print(j)

[24 'M' 'technician' '85711']
24
M
technician
85711
[53 'F' 'other' '94043']
53
F
other
94043
[23 'M' 'writer' '32067']
23
M
writer
32067
[24 'M' 'technician' '43537']
24
M
technician
43537
[33 'F' 'other' '15213']
33
F
other
15213
[42 'M' 'executive' '98101']
42
M
executive
98101
[57 'M' 'administrator' '91344']
57
M
administrator
91344
[36 'M' 'administrator' '05201']
36
M
administrator
05201
[29 'M' 'student' '01002']
29
M
student
01002
[53 'M' 'lawyer' '90703']
53
M
lawyer
90703
[39 'F' 'other' '30329']
39
F
other
30329
[28 'F' 'other' '06405']
28
F
other
06405
[47 'M' 'educator' '29206']
47
M
educator
29206
[45 'M' 'scientist' '55106']
45
M
scientist
55106
[49 'F' 'educator' '97301']
49
F
educator
97301
[21 'M' 'entertainment' '10309']
21
M
entertainment
10309
[30 'M' 'programmer' '06355']
30
M
programmer
06355
[35 'F' 'other' '37212']
35
F
other
37212
[40 'M' 'librarian' '02138']
40
M
librarian
02138
[42 'F' 'homemaker' '95660']
42
F
homemaker
95660
[26 'M' 'writer' '30068']
26
M

### Step 10. What is the data type of each column?
Solve it by 2 different ways

In [114]:
users.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 943 entries, 1 to 943
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   age         943 non-null    int64 
 1   gender      943 non-null    object
 2   occupation  943 non-null    object
 3   zip_code    943 non-null    object
dtypes: int64(1), object(3)
memory usage: 69.1+ KB


In [116]:
var = users.dtypes
var

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

In [118]:
print(type(var))

<class 'pandas.core.indexes.base.Index'>


In [119]:
print(var.index)

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')


In [120]:
print(var.values)

[dtype('int64') dtype('O') dtype('O') dtype('O')]


### Step 11. Print only the occupation column
Solve it by 2 different ways

In [128]:
users.occupation

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...      
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

In [129]:
users['occupation']

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...      
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

In [134]:
users['occupation'].shape

(943,)

In [132]:
pd.DataFrame(users['occupation']).shape

(943, 1)

In [135]:
np.array(users['occupation'])

array(['technician', 'other', 'writer', 'technician', 'other',
       'executive', 'administrator', 'administrator', 'student', 'lawyer',
       'other', 'other', 'educator', 'scientist', 'educator',
       'entertainment', 'programmer', 'other', 'librarian', 'homemaker',
       'writer', 'writer', 'artist', 'artist', 'engineer', 'engineer',
       'librarian', 'writer', 'programmer', 'student', 'artist',
       'student', 'student', 'administrator', 'homemaker', 'student',
       'student', 'other', 'entertainment', 'scientist', 'engineer',
       'administrator', 'librarian', 'technician', 'programmer',
       'marketing', 'marketing', 'administrator', 'student', 'writer',
       'educator', 'student', 'programmer', 'executive', 'programmer',
       'librarian', 'none', 'programmer', 'educator', 'healthcare',
       'engineer', 'administrator', 'marketing', 'educator', 'educator',
       'student', 'student', 'student', 'engineer', 'engineer',
       'scientist', 'administrator', 'st

In [136]:
np.array(pd.DataFrame(users['occupation']))

array([['technician'],
       ['other'],
       ['writer'],
       ['technician'],
       ['other'],
       ['executive'],
       ['administrator'],
       ['administrator'],
       ['student'],
       ['lawyer'],
       ['other'],
       ['other'],
       ['educator'],
       ['scientist'],
       ['educator'],
       ['entertainment'],
       ['programmer'],
       ['other'],
       ['librarian'],
       ['homemaker'],
       ['writer'],
       ['writer'],
       ['artist'],
       ['artist'],
       ['engineer'],
       ['engineer'],
       ['librarian'],
       ['writer'],
       ['programmer'],
       ['student'],
       ['artist'],
       ['student'],
       ['student'],
       ['administrator'],
       ['homemaker'],
       ['student'],
       ['student'],
       ['other'],
       ['entertainment'],
       ['scientist'],
       ['engineer'],
       ['administrator'],
       ['librarian'],
       ['technician'],
       ['programmer'],
       ['marketing'],
       ['marketing'],
 

In [139]:
print(users['occupation'].to_string(index=False))

user_id
   technician
        other
       writer
   technician
        other
    executive
administrator
administrator
      student
       lawyer
        other
        other
     educator
    scientist
     educator
entertainment
   programmer
        other
    librarian
    homemaker
       writer
       writer
       artist
       artist
     engineer
     engineer
    librarian
       writer
   programmer
      student
       artist
      student
      student
administrator
    homemaker
      student
      student
        other
entertainment
    scientist
     engineer
administrator
    librarian
   technician
   programmer
    marketing
    marketing
administrator
      student
       writer
     educator
      student
   programmer
    executive
   programmer
    librarian
         none
   programmer
     educator
   healthcare
     engineer
administrator
    marketing
     educator
     educator
      student
      student
      student
     engineer
     engineer
    scientis

### Step 12. How many different occupations are in this dataset? How many users per occupation are in the dataset?

In [147]:
users['occupation'].unique()

array(['technician', 'other', 'writer', 'executive', 'administrator',
       'student', 'lawyer', 'educator', 'scientist', 'entertainment',
       'programmer', 'librarian', 'homemaker', 'artist', 'engineer',
       'marketing', 'none', 'healthcare', 'retired', 'salesman', 'doctor'],
      dtype=object)

In [150]:
len(users['occupation'].unique())

21

In [151]:
users['occupation'].nunique()

21

In [149]:
# set(users['occupation'])

In [158]:
users['occupation'].value_counts(normalize=True)

student          0.207847
other            0.111347
educator         0.100742
administrator    0.083775
engineer         0.071050
programmer       0.069989
librarian        0.054083
writer           0.047720
executive        0.033934
scientist        0.032874
artist           0.029692
technician       0.028632
marketing        0.027572
entertainment    0.019088
healthcare       0.016967
retired          0.014846
lawyer           0.012725
salesman         0.012725
none             0.009544
homemaker        0.007423
doctor           0.007423
Name: occupation, dtype: float64

### Step 13. What is the most frequent occupation?

In [161]:
users['occupation'].value_counts().index[0]

'student'

In [163]:
users['occupation'].value_counts().idxmax()

'student'

In [166]:
users['occupation'].mode()

0    student
dtype: object

### Step 14. Summarize the DataFrame.  Use describe()

In [168]:
users.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 943 entries, 1 to 943
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   age         943 non-null    int64 
 1   gender      943 non-null    object
 2   occupation  943 non-null    object
 3   zip_code    943 non-null    object
dtypes: int64(1), object(3)
memory usage: 69.1+ KB


In [174]:
users.describe()

age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

### Step 15. Summarize all the columns. Use describe()

In [175]:
users.describe(include="all")

age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [178]:
users['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

In [179]:
users['age'].mean()

34.05196182396607

In [180]:
np.mean(users['age'])

34.05196182396607

### Step 18. What is the age with least occurrence?

In [198]:
users['age'].value_counts().tail(10)

70    3
62    2
68    2
64    2
69    2
7     1
66    1
11    1
10    1
73    1
Name: age, dtype: int64

In [201]:
users['age'].unique()

array([24, 53, 23, 33, 42, 57, 36, 29, 39, 28, 47, 45, 49, 21, 30, 35, 40,
       26, 25, 32, 41,  7, 38, 20, 19, 27, 18, 22, 37, 16, 50, 31, 51, 17,
       48, 34, 43, 60, 55, 15, 61, 44, 54, 59, 46, 13, 52, 56, 14, 66, 62,
       11, 65, 68, 63, 64, 10, 73, 58, 69, 70], dtype=int64)

In [205]:
edades_0 = []
for i in range(10, 75):
    if i not in users['age'].unique():
        edades_0.append(i)

In [206]:
print(edades_0)

[12, 67, 71, 72, 74]
